import "./globals.css";
import type { Metadata } from "next";
import localfont from "next/font/local";
import { Inter } from "next/font/google";

import NonSSRWrapper from "./components/noSSRWrapper/NoSSRWrapper";
import AuthProvider from "./provider";
import { ReduxProvider } from "@/redux/reduxProvider";

import { ToastContainer } from "react-toastify";
// -----------------------------------------------------------------

// custom font
const interFont = localfont({
  src: [
    {
      path: "../../public/fonts/Inter-Regular.ttf",
      weight: "500",
    },
  ],
  variable: "--font-inter",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Youapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${interFont.variable}`}>
        <NonSSRWrapper>
          <AuthProvider>
            <ReduxProvider>
              {children}
              <ToastContainer />
            </ReduxProvider>
          </AuthProvider>
        </NonSSRWrapper>
      </body>
    </html>
  );
}
